name: DGCI

on: [ push, pull_request ]
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        id: pkgversion
        run: |
          PKG_VERSION=$(jq -r ".version" "package.json")
          echo "$PKG_VERSION"
          echo "::set-output name=PKG_VERSION::$PKG_VERSION"
      - name: echo version
        run: |
          echo "version is ${{ steps.pkgversion.outputs.PKG_VERSION }}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: someimage
          tags: |
            type=raw,value=latest
            type=raw,value=dev-{{date 'YYYYMMDD'}}-{{sha}}
            type=raw,value=dev-${{ steps.pkgversion.outputs.PKG_VERSION }}

      - name: echo docker meta
        id: echo-docker-meta
        run: |
          echo ${{ steps.pkgversion.outputs.PKG_VERSION }}
